### ISSUE TITLE
database

### ISSUE THREAD

**Issue by rassim-medkour** [max3no/spring-security-jwt-mysql#1]
what are the tables used in the database and preferably the code for them should be uploaded aswell that would make it perfect.

**Comment by max3no** [comment]
Tables are mentioned in the Entities, they will automatically be created.
you need to just create a database and add that name in application.properties file
spring.datasource.url= jdbc:mysql://localhost:3306/**someapp**
where someapp will be the name of the database.
Just run these two commands to insert roles in your db after running the project for the first time
INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
This is mentioned in the Readme file.

Thank you
